### ISSUE TITLE
Error on Bitrise integration

### ISSUE THREAD

**Issue by DavisJP** [oversecured/oversecured-bitrise-step#1]
I'm following this guide [here](https://oversecured.com/docs/ci-cd/bitrise) to integrate Oversecured to our Bitrise CI but keep getting this error:

oversecured: Step 'Signed URL' failed with code 422, server message: Validation Failed

Any place I can get more information about it?

**Comment by bagipro** [comment]
Hi @DavisJP,

Thanks for reporting the issue! We're looking at it

**Comment by bagipro** [comment]
@DavisJP,
Can you make sure that APK was already generated before running Oversecured step? E.g. you need to place Gradle Runner and Deploy to Bitrise.io steps higher than Oversecured. This error happens when the APK file is missing on the defined path.

We will add more helpful error messages for such cases.

**Comment by DavisJP** [comment]
@bagipro Thanks for checking so quickly but the step was after the deploy step. I will check again later the path but adding more error messages would surely be helpful.

Thanks.

**Comment by DavisJP** [comment]
Closing the issue as not using the integration anymore.
